name: Steam Releases

on:
  push:
    tags:
      - v*.*
  workflow_dispatch:
    inputs:
      demo:
        description: 'Release demo'
        type: boolean
        default: false
      release-steam:
        description: 'Release for steam'
        type: boolean
        default: false
      release-github:
        description: 'Release for discord'
        type: boolean
        default: false
      release-itch:
        description: 'Release for itch.io'
        type: boolean
        default: false

env:
  STEAM_APP: 3191960
  STEAM_DEMO_APP: 3196670
  STEAM_BRANCH: beta

jobs:
  release-info:
    runs-on: ubuntu-latest
    outputs:
      steam_id: ${{ steps.steam-app.outputs.steam_id }}
    steps:
      - id: steam-app
        run: |
          STEAM_ID=${STEAM_APP:-430}
          IS_DEMO=${DEMO:-false}

          if [ $IS_DEMO = true ] || [[ "$REF" =~ "-demo" ]]; then
            STEAM_ID=$STEAM_DEMO_APP
          fi

          echo "::debug::Steam App ID: $STEAM_ID"
          echo "steam_id=$STEAM_ID" >> $GITHUB_OUTPUT
        env:
          DEMO: ${{ inputs.demo }}
          REF: ${{ github.ref_name }}
  
  build-godot:
    uses: kuma-gee/.github/workflows/godot-build.yml@main
    needs: release-info
    with:
      channels: '["windows", "linux"]'
      steam-app: ${{ fromJSON(needs.release-info.outputs.steam_id) }}
      godot-version: 4.3
      project-path: godot
    secrets: inherit

  release-itch:
    uses: kuma-gee/.github/workflows/itch-release.yml@main
    needs: build-godot
    if: ${{ inputs.release-itch && inputs.demo }}
    with:
      channels: '["web"]'
      game: ${{ needs.build-godot.outputs.game }}
      itch-user: ${{ secrets.ITCHIO_USER }}
    secrets:
      BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
      PASSWORD: ${{ needs.build-godot.outputs.password }}
  
  release-steam:
    uses: kuma-gee/.github/workflows/steam-release.yml@main
    needs: build-godot
    if: ${{ inputs.release-steam }}
    with:
      steam-app: ${{ fromJSON(needs.release-info.outputs.steam_id) }}
      branch: ${{ env.STEAM_BRANCH }}
    secrets:
      STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
      STEAM_CONFIG_VDF: ${{ secrets.STEAM_CONFIG_VDF }}
      PASSWORD: ${{ needs.build-godot.outputs.password }}

  release-github:
    uses: kuma-gee/.github/workflows/github-release.yml@main
    needs: build-godot
    if: ${{ inputs.release-github }}
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_RELEASE_HOOK }}
      PASSWORD: ${{ needs.build-godot.outputs.password }}