name: Releases

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Steam branch to release'
        type: string
        default: ''
      notify:
        description: 'Notify on discord'
        type: boolean
        default: true
      demo:
        description: 'Release demo'
        type: boolean
        default: false

jobs:
  release-steam-github:
    uses: kuma-gee/action-godot/.github/workflows/steam-release.yml@main
    with:
      branch: ${{ github.event.inputs.branch }}
      notify: ${{ github.event.inputs.notify == 'true' }}
      demo: ${{ github.event.inputs.demo == 'true' }}
    secrets: inherit