name: Releases

on:
  push:
    tags:
      - v*.*
  workflow_dispatch:
    inputs:
      branch:
        description: 'Steam branch to release'
        type: string
        default: 'beta'
      release-discord:
        description: 'Release for discord'
        type: boolean
        default: true
      demo:
        description: 'Release demo'
        type: boolean
        default: false

env:
  STEAM_APP: 3191960
  STEAM_DEMO_APP: 3196670

jobs:
  release-info:
    runs-on: ubuntu-latest
    outputs:
      steam_id: ${{ steps.steam-app.outputs.id }}
    steps:
      - id: steam-app
        run: |
          STEAM_ID=$STEAM_APP

          if [ $DEMO = true ] || [[ $REF =~ "-demo" ]]; then
            STEAM_ID=$STEAM_DEMO_APP
          fi

          echo "::debug::Steam App ID: $STEAM_ID"
          echo "steam_id=$STEAM_ID" >> $GITHUB_OUTPUT
        env:
          DEMO: ${{ inputs.demo }}
          REF: ${{ github.ref_name }}

  generate-password:
    runs-on: ubuntu-latest
    outputs:
      password: ${{ steps.random-password.outputs.password }}
    steps:
      - uses: actions/checkout@v4
      - uses: kuma-gee/action-godot/password@main
        id: random-password
        with:
          length: 24

  release-steam-github:
    uses: kuma-gee/action-godot/.github/workflows/steam-release.yml@main
    needs: [release-info, generate-password]
    with:
      steam_app: ${{ fromJSON(needs.steam-app.outputs.steam_id) }}
      branch: ${{ inputs.branch }}
      godot-version: 4.3
      project-path: godot
      assets-path: assets
      env-build-file: build.gd
      release-discord: ${{ fromJSON(inputs.release-discord) }}
    secrets:
      STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
      STEAM_CONFIG_VDF:   ${{ secrets.STEAM_CONFIG_VDF }}
      ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
      GAME_CODE: ${{ secrets.GAME_CODE }}
      ASSETS_PASSWORD: ${{ secrets.ASSETS_PASSWORD }}
      DISCORD_RELEASE_HOOK: ${{ secrets.DISCORD_RELEASE_HOOK }}
      ARCHIVE_PASSWORD: ${{ needs.generate-password.outputs.password }}