name: Releases

on:
  workflow_call:
    inputs:
      branch:
        description: 'Steam branch to release'
        type: string
        default: ''
      release-discord:
        description: 'Release for discord'
        type: boolean
        default: false
      demo:
        description: 'Release demo'
        type: boolean
        default: false
  workflow_dispatch:
    inputs:
      branch:
        description: 'Steam branch to release'
        type: string
        default: ''
      release-discord:
        description: 'Release for discord'
        type: boolean
        default: false
      demo:
        description: 'Release demo'
        type: boolean
        default: false

env:
  STEAM_APP: 3191960
  STEAM_DEMO_APP: 3196670

jobs:
  steam-app:
    runs-on: ubuntu-latest
    outputs:
      id: ${{ steps.steam-app.outputs.id }}
    steps:
      - id: steam-app
        run: |
          STEAM_ID=$STEAM_APP
          if [ $DEMO = true ]; then
            STEAM_ID=$STEAM_DEMO_APP
          fi

          echo "::debug::Steam App ID: $STEAM_ID"
          echo "id=$STEAM_ID" >> $GITHUB_OUTPUT
        env:
          DEMO: ${{ inputs.demo }}

  generate-password:
    runs-on: ubuntu-latest
    outputs:
      password: ${{ steps.random-password.outputs.password }}
    steps:
      - uses: actions/checkout@v4
      - uses: kuma-gee/action-godot/password@main
        id: random-password
        with:
          length: 24

  release-steam-github:
    uses: kuma-gee/action-godot/.github/workflows/steam-release.yml@main
    needs: [steam-app, generate-password]
    with:
      steam_app: ${{ fromJSON(needs.steam-app.outputs.id) }}
      branch: ${{ inputs.branch }}
      godot-version: 4.3
      project-path: godot
      assets-path: assets
      env-build-file: build.gd
      password: ${{ needs.generate-password.outputs.password }}
      release-discord: ${{ fromJSON(inputs.release-discord) }}
    secrets: inherit