name: Releases

on:
  push:
    tags:
      - v*.*
  workflow_dispatch:
    inputs:
      branch:
        description: 'Steam branch to release'
        type: string
        default: ''
      release-discord:
        description: 'Release for discord'
        type: boolean
        default: false
      demo:
        description: 'Release demo'
        type: boolean
        default: false

env:
  STEAM_APP: 3191960
  STEAM_DEMO_APP: 3196670

jobs:
  release-info:
    runs-on: ubuntu-latest
    outputs:
      steam_id: ${{ steps.steam-app.outputs.steam_id }}
      branch: ${{ steps.steam-app.outputs.branch }}
      discord: ${{ steps.steam-app.outputs.discord }}
    steps:
      - id: steam-app
        run: |
          STEAM_ID=${STEAM_APP:-430}
          IS_DEMO=${DEMO:-false}
          RELEASE_DISCORD=${DISCORD:-false}
          BRANCH=${BRANCH:-""}

          if [ $IS_DEMO = true ] || [[ "$REF" =~ "-demo" ]]; then
            STEAM_ID=$STEAM_DEMO_APP
          fi

          if [ $IS_TAG = true ]; then
            BRANCH="beta"
            RELEASE_DISCORD=true
          fi

          echo "::debug::Steam App ID: $STEAM_ID"

          echo "steam_id=$STEAM_ID" >> $GITHUB_OUTPUT
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT
          echo "discord=$RELEASE_DISCORD" >> $GITHUB_OUTPUT
        env:
          DEMO: ${{ inputs.demo }}
          BRANCH: ${{ inputs.branch }}
          DISCORD: ${{ inputs.release-discord }}
          REF: ${{ github.ref_name }}
          IS_TAG: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') }}

  release-steam-github:
    uses: kuma-gee/action-godot/.github/workflows/steam-release.yml@main
    needs: release-info
    with:
      steam_app: ${{ fromJSON(needs.release-info.outputs.steam_id) }}
      branch: ${{ needs.release-info.outputs.branch }}
      godot-version: 4.3
      project-path: godot
      assets-path: assets
      env-build-file: build.gd
      release-discord: ${{ needs.release-info.outputs.discord }}
    secrets: inherit