name: Releases

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Steam branch to release'
        type: string
        default: ''
      release-discord:
        description: 'Release for discord'
        type: boolean
        default: false
      demo:
        description: 'Release demo'
        type: boolean
        default: false

jobs:
  release-steam-github:
    uses: kuma-gee/action-godot/.github/workflows/steam-release.yml@main
    with:
      branch: ${{ github.event.inputs.branch }}
      release-discord: ${{ github.event.inputs.release-discord == 'true' }}
      demo: ${{ github.event.inputs.demo == 'true' }}
    secrets: inherit