name: Releases

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Steam branch to release'
        type: string
        default: ''
      release-discord:
        description: 'Release for discord'
        type: boolean
        default: false
      demo:
        description: 'Release demo'
        type: boolean
        default: false

env:
  STEAM_APP: 3191960
  STEAM_DEMO_APP: 3196670

jobs:
  steam-app:
    runs-on: ubuntu-latest
    outputs:
      id: ${{ steps.steam-app.outputs.id }}
    steps:
      - id: steam-app
        run: |
          STEAM_ID=$STEAM_APP
          if [ $DEMO = true ]; then
            STEAM_ID=$STEAM_DEMO_APP
          fi

          echo "id=$STEAM_ID" >> $GITHUB_OUTPUT
        env:
          DEMO: ${{ github.event.inputs.demo }}

  release-steam-github:
    uses: kuma-gee/action-godot/.github/workflows/steam-release.yml@main
    needs: steam-app
    with:
      steam_app: ${{ needs.steam-app.outputs.id }}
      branch: ${{ github.event.inputs.branch }}
      godot-version: 4.3
      project-path: godot
      assets-path: assets
      env-build-file: build.gd
      release-discord: ${{ github.event.inputs.release-discord == 'true' }}
    secrets: inherit