name: Release on tag

on:
  push:
    tags:
      - v*.*

jobs:
  release-info:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.info.outputs.branch }}
      release-discord: ${{ steps.info.outputs.discord }}
      demo: ${{ steps.info.outputs.demo }}
    steps:
      - id: info
        run: |
          DEMO=false
          if [[ $TAG =~ "-demo" ]];
            DEMO=true
          fi

          echo "branch=beta" >> $GITHUB_OUTPUT
          echo "discord=true" >> $GITHUB_OUTPUT
          echo "demo=$DEMO" >> $GITHUB_OUTPUT
        env:
          TAG: ${{ github.ref_name }}

  release-tag:
    uses: .github/workflows/release.yml
    needs: release-info
    with:
      branch: ${{ needs.release-info.outputs.branch }}
      release-discord: ${{ needs.release-info.outputs.release-discord }}
      demo: ${{ needs.release-info.outputs.demo }}
